### ISSUE TITLE
CESR "in-memory" field map referenced in the spec?

### ISSUE THREAD

**Issue by daidoji** [trustoverip/tswg-cesr-specification#65]
In the https://trustoverip.github.io/tswg-cesr-specification/#version-string-field-format section we have: 

>The last one, CESR, is used to represent CESR when the field map is converted to an in-memory data object so that it might be converted more conveniently back to the appropriate serialization. The native CESR serialization of a field map does not need a serialization type.

This is a little confusing for a few reasons:

1. How do we peek at the "in-memory" fieldmap without the version string peeking we do for CBOR, MGPK, JSON?  Where is the `value` (from our TLV scheme) obtained from a field map that's streamed from an "in-memory" data object similar to the other field map types?
2. What serializations do we support?  (ie what would a Haskell map serialization look like in this format?)
3. How would we peek using a regular expression for this type of version?  Do we need to also specify an encoding when encountering this? 
4. The native CESR serialization field map does not need a serialization type seems inconsistent with the scheme.  Is this really intended?

Maybe these two lines are left over from some previous iteration because right now they stick out a bit inconsistently from the rest of the scheme.

**Comment by SmithSamuelM** [comment]
@daidoji Now that I read in in context I realize the confusion

"The last one, CESR, is used to represent `CESR` when the field map is converted to an in-memory data object so that it might be converted more conveniently back to the appropriate serialization. The native CESR serialization of a field map does not need a serialization type. "

Let me try to reword it.

The last one, CESR is special. A CESR native serialization of a field map may use either the    `-G##` or  `-0G#####` count codes to indicate that it is a field map. Because count codes have unique start bits (see the section on Performant resynchronization) there is no need to embed a regular expression parsable version string field in a CESR native field map. Because a CESR native field map does not include a version string field embedded in its field map, once deserialized into an in-memory data object representation of that field map, there is no normative indication that the in-memory object was deserialized from a  CESR native field map.   This indication would otherwise have to be provided externally.  Instead, the in-memory object representation of the  field map may inject a placeholder version string, `v` field whose value is a version string but with the serialization kind set to `CESR`. This way when re-serializing there is a normative indicator to reserialize as a CESR native field map and not JSON, CBOR, or MGPK.

**Comment by SmithSamuelM** [comment]
> How do we peek at the "in-memory" fieldmap without the version string peeking we do for CBOR, MGPK, JSON? Where is the value (from our TLV scheme) obtained from a field map that's streamed from an "in-memory" data object similar to the other field map types?

Why would anyone be peeking at in in memory field map object. Its not a serialization it is an object that the language in which it is represented allows asynchnous access. For example, in python a field map is called a dict. Suppose that in  python I have a dict object assigned to varable d. If I want to access the value of the field with label "v" I just put this in my code v =d["v"}. If I want to iterate over all the field labels in my dict I use the following cod:   d.keys()   or the items in the dict d.items().   In memory objects are not serlializations in the sense of a protocol they are however the language compiler etc lays them out. We are not doing a memory scan to access them (unless you are doing low level debugging).

What serializations do we support? (ie what would a Haskell map serialization look like in this format?)
How would we peek using a regular expression for this type of version? Do we need to also specify an encoding when encountering this?

This has nothing to do with serialization per se but how a serialization is deserialized into a given "object".

The native CESR serialization field map does not need a serialization type seems inconsistent with the scheme. Is this really intended?

See my answer above.

**Comment by daidoji** [comment]
@SmithSamuelM ahh thanks.  The first answer cleared it up and the second answer was exactly what I was confused about "why would someone do that?"  

That being said, adding the rationale for the in-memory representations for that placeholder version string utilizing a kind of CESR and use for in memory data structures would provide a lot of clarity I think.  Right now I think that's the only place its mentioned.

**Comment by SmithSamuelM** [comment]
Great I will revise to use the suggested revision.

**Comment by SmithSamuelM** [comment]
Fixed with pull request #72
